#!/bin/bash

#Credits
: '
ALL ART IS CREDITED TO ORIGINAL ARTIST WHEN APPLICABLE

ART SOURCES: https://www.asciiart.eu/
'
#VARIABLES

ELIFCT=$(grep -c 'elif' /usr/bin/shell-random-greeter ) #counts the #of Else-If statements in file (ADDED FOR EASIER CUSTOMIZATION)
RANGE=$((ELIFCT - 3))
RANDINT=$(($RANDOM% $RANGE )) 
CURRENT_TIME=$( date '+%H:%M:%S') 
##############################################################################################################

function welcome() { #Welcome script 
	echo 'Welcome!' $USER'@'$HOSTNAME
	echo "Your Current Directory is: " $PWD
	echo "Time of Terminal Start: " $CURRENT_TIME
		if [[ $SHELL =~ zsh ]]; then #If the shell is ZSH
			echo 'Your default shell is: ZSH'
		elif [[ $SHELL =~ bash ]]; then #If the shell is BASH 
			echo 'Your default shell is: BASH'
		elif [[ $SHELL =~ fish ]]; then #If the shell is FISH -1
			echo 'Your default shell is: FISH'
		elif [[ $SHELL =~ ksh ]]; then #If the shell is KSH -2
			echo 'Your default shell is: KSH'
		elif [[ $SHELL =~ tcsh ]]; then #If the shell is TCSH -3
			echo 'Your default shell is: TCSH'
		else #IF shell is unknown
			echo "!!! Can't detect your shell. Printing Shell dir: " $SHELL 
		fi
	echo '____________________________________'
	echo
}

welcome

#ART and Quotes
if [[ $RANDINT == 0 ]]; then #AOT
	echo '============================='
	echo '-------{心臓を捧げよ!}-------'
	echo '---{Dedicate your hearts!}---'
	echo '----{!Shinzō o Sasageyo!}----'
	echo '============================='
	echo '- From Attack On Titan (進撃の巨人)'

elif [[ $RANDINT == 1 ]]; then #Outsiders 
	echo '@=================================@'
	echo '!------{STAY GOLDEN PONYBOY}------!'
	echo '@=================================@'
	echo '- Dallas, The Outsiders'

elif [[ $RANDINT == 2 ]]; then #Who gave you perms????
	echo ' #***************************************# '
	echo '===Who gave you permission to launch me?==='
	echo ' #***************************************# '

elif [[ $RANDINT == 3 ]]; then #WHO 
	echo ' #**************************# '
	echo '===WHO IN THE FRICK ARE YOU?==='
	echo ' #**************************# '
	echo 
	echo "(Oh, it's just you," $USER ")"

elif [[ $RANDINT == 4 ]]; then #Forest Gump
	echo ' #***********************************# '
	echo '== Life is like a box of Chocalates. =='
	echo ' #***********************************# '
	echo '- Forrest Gump'
elif [[ $RANDINT == 5 ]]; then #Mishima
	echo ' #******************************************# '
	echo '=== The instant that the blade tore open ====='
	echo '=== his flesh, the bright disk of the sun ====' 
	echo '== soared up and exploded behind his eyelids.='
	echo ' #******************************************# '
	echo ' - Runaway Horses, Yukio Mishima' 


elif [[ $RANDINT == 6 ]]; then #HACKING THE PENTAGON
	echo '+++HACKING THE PENTAGON+++'
	echo 'Progress: [#####################]'
	echo 'Done! Giving' [ $USER ] 'root access now...'
	echo 'TIME OF ACCESS: ' $CURRENT_TIME

elif [[ $RANDINT == 7 ]]; then #Trollface	
	echo '     ▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄        '
	echo '     █░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄    '
	echo '    █░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█   '
	echo '   █░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█  '
	echo ' ▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█ '
	echo '█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█'
	echo '█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█'
	echo ' █░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█ '
	echo '  █░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█  '
	echo '   █░░░░██░░▀█▄▄▄█▄▄█▄████░█   '
	echo '    █░░░░▀▀▄░█░░░█░█▀██████░█  '
	echo '     ▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█  ' 
	echo '       ▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█ '
	echo '          ▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█ '
	echo '              ▀▄▄▄▄▄░░░░░░░░█  ' 
	echo '    Problem?        ▀▀▀▀▀▀▀▀   '
	echo '    AsciiArt From: TwitchQuotes' 

elif [[ $RANDINT == 8 ]]; then
	echo '   SMOKE DAT       (  )/     '
	echo '    JUNGLEBOYZ      )(/      '
	echo ' ________________  ( /)      '
	echo '()__)____________)))))    hjw'
	echo 'AsciiArt by: Hayley Jane Wakenshaw | Source Asciiart.eu'

elif [[ $RANDINT == 9 ]]; then 
	echo '              ...                             '
	echo '             ;::::;                           ' 
	echo '            ;::::; :;                         '
	echo "         ;:::::'   :;                         "
	echo "        ;:::::;     ;.                        "
	echo "       ,:::::'       ;           OOO\         "  
	echo "       ::::::;       ;          OOOOO\        "
	echo "       ;:::::;       ;         OOOOOOOO       "
	echo "      ,;::::::;     ;'         / OOOOOOO      "
	echo '    ;:::::::::`. ,,,;.        /  / DOOOOOO    '
	echo "  .';:::::::::::::::::;,     /  /     DOOOO   "
	echo " ,::::::;::::::;;;;::::;,   /  /        DOOO  "
	echo ';`::::::` ::::::;;;::::: ,#/  /          DOOO '
	echo ':`:::::::`;::::::;;::: ;::#  /            DOOO'
	echo '::`:::::::`;:::::::: ;::::# /              DOO'
	echo '`:`:::::::`;:::::: ;::::::#/               DOO'
	echo ' :::`:::::::`;; ;:::::::::##                OO'
	echo ' ::::`:::::::`;::::::::;:::#                OO' 
	echo ' `:::::`::::::::::::; `:;::#                O '
	echo '  `:::::`::::::::;  /  / `:#                  ' 
	echo '   ::::::`:::::;   /  /   `#                  '
	echo 'Unknown Artist: Source: Asciiart.eu' 

elif [[ $RANDINT == 10 ]]; then
	echo "TESTING TESTING? MIC CHECK: OK!"

else
	echo '|=====__-__=====|'
	echo '|DanceDanceRate4|'
	echo '[===============]'
fi

#END OF ART

echo '____________________________________'
echo 

#DEBUG MENU (uncomment to use)
: '
echo "DEBUG MENU:"
echo "========================"
echo "RANGE: " $RANGE
echo "RANDINT:" $RANDINT
echo "ELIFct:" $ELIFCT
'
